language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
env:
  - SOLIDITY_COVERAGE=false
install:
  - yarn
before_script:
- truffle version
script:
  - yarn lint
  - yarn test
after_script:
  - yarn coverage && cat coverage/lcov.info | node_modules/.bin/coveralls
