language: node_js
node_js:
  - '8'
cache:
  directories:
  - node_modules
env:
  - SOLIDITY_COVERAGE=false
install:
  - npm install
before_script:
- truffle version
script:
  - npm test
after_script:
  - npm run coverage && cat coverage/lcov.info | node_modules/.bin/coveralls
