language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
env:
  - SOLIDITY_COVERAGE=false
  - TEST_COMMAND=lint
  - TEST_COMMAND=test
install:
  - yarn
before_script:
- truffle version
script:
  - "yarn $TEST_COMMAND"
  - "yarn $TEST_COMMAND"
after_script:
  - yarn coverage && cat coverage/lcov.info | node_modules/.bin/coveralls
