language: node_js
node_js:
  - '10'
cache:
  directories:
  - node_modules
install:
  - yarn
matrix:
  include:
    - name: "Lint"
      script: yarn lint
    - name: "Test"
      env: SOLIDITY_COVERAGE=false
      script: yarn test
    - name: "Coverage"
      script: yarn coverage && cat coverage/lcov.info | node_modules/.bin/coveralls
